name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 17 (since your system uses Java 17.0.12)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Compile all Java files
      - name: Compile Java files
        run: |
          mkdir -p out
          javac -d out $(find . -name "*.java")

      # Step 4: Run all classes that contain a `main` method
      - name: Run Java programs
        run: |
          for classfile in $(find out -name "*.class"); do
            classname=$(echo "$classfile" | sed 's|out/||;s|/|.|g;s|.class$||')
            echo "▶ Running $classname"
            java -cp out "$classname" || true
          done
